# Config file for automatic testing at travis-ci.org

sudo: false

language: python

python:
  - "3.4"
  - "3.3"
  - "2.7"

services:
  - mongodb

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -r requirements-dev.txt

# command to run tests, e.g. python setup.py test
script: coverage run --source flask_musers runtests.py

after_success: coveralls
